//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackspotIE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suburb
    {
        public Suburb()
        {
            this.Accidents = new HashSet<Accident>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Postcode { get; set; }
        public string Geometry { get; set; }
        public string Lat { get; set; }
        public string Long { get; set; }
    
        public virtual ICollection<Accident> Accidents { get; set; }
    }
}
